# Generated by Django 5.2.3 on 2025-11-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
