# Generated by Django 5.2.3 on 2025-11-14 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0002_folder_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage_app.folder'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage_app.file'),
        ),
    ]
