# Generated by Django 5.2.3 on 2025-11-15 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0004_folder_is_deleted_trash_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='require_password',
            field=models.BooleanField(default=False),
        ),
    ]
