# Generated by Django 5.2.3 on 2025-11-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0005_sharelink_password_hash_sharelink_require_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
