# Generated by Django 5.2.3 on 2025-11-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_app', '0006_folder_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageplan',
            name='max_file_size',
            field=models.BigIntegerField(default=104857600, help_text='Maximum allowed file size per upload in bytes'),
        ),
    ]
